-- MySQL Script generated by MySQL Workbench
-- Tue Dec 11 18:29:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8 ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Cliente` (
  `cod_cliente` INT NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `local_trabalho` VARCHAR(45) NULL,
  `fone_residencial` VARCHAR(11) NULL,
  `fone_celular` VARCHAR(11) NULL,
  `fone_comercial` VARCHAR(11) NULL,
  `sexo` VARCHAR(10) NULL,
  `data_nascimento` DATE NULL,
  `status` INT NULL,
  PRIMARY KEY (`cod_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Genero` (
  `cod_genero` INT NOT NULL,
  `descricao` VARCHAR(20) NULL,
  PRIMARY KEY (`cod_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Fornecedor` (
  `cod_fornecedor` INT NOT NULL,
  `cnpj` VARCHAR(14) NULL,
  `razao_social` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NULL,
  `pessoa_contato` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Filme` (
  `cod_filme` INT NOT NULL,
  `titulo_original` VARCHAR(45) NULL,
  `titulo_portugues` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `ano` INT NULL,
  `direcao` VARCHAR(45) NULL,
  `elenco` VARCHAR(200) NULL,
  `sinopse` VARCHAR(2000) NULL,
  `duracao` VARCHAR(45) NULL,
  `categoria` VARCHAR(12) NULL,
  `cod_genero` INT NOT NULL,
  `Fornecedor_cod_fornecedor` INT NOT NULL,
  PRIMARY KEY (`cod_filme`),
  INDEX `fk_Filme_Genero1_idx` (`cod_genero` ASC) VISIBLE,
  INDEX `fk_Filme_Fornecedor1_idx` (`Fornecedor_cod_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Filme_Genero1`
    FOREIGN KEY (`cod_genero`)
    REFERENCES `locadora`.`Genero` (`cod_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filme_Fornecedor1`
    FOREIGN KEY (`Fornecedor_cod_fornecedor`)
    REFERENCES `locadora`.`Fornecedor` (`cod_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`TipoMidia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`TipoMidia` (
  `cod_tipomidia` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`cod_tipomidia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Dependente` (
  `cod_dependente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `sexo` VARCHAR(10) NULL,
  `data_nascimento` DATE NULL,
  `Cliente_cod_cliente` INT NOT NULL,
  PRIMARY KEY (`cod_dependente`),
  INDEX `fk_Dependente_Cliente1_idx` (`Cliente_cod_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Dependente_Cliente1`
    FOREIGN KEY (`Cliente_cod_cliente`)
    REFERENCES `locadora`.`Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`ItemFilme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`ItemFilme` (
  `cod_item_filme` INT NOT NULL,
  `cod_filme` INT NOT NULL,
  `data_aquisicao` DATE NULL,
  `numero_serie` VARCHAR(20) NULL,
  `cod_tipomidia` INT NOT NULL,
  PRIMARY KEY (`cod_item_filme`, `cod_filme`),
  INDEX `fk_Fornecedor_has_Filme_Filme1_idx` (`cod_filme` ASC) VISIBLE,
  INDEX `fk_Fornece_TipoMidia1_idx` (`cod_tipomidia` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Filme_Filme1`
    FOREIGN KEY (`cod_filme`)
    REFERENCES `locadora`.`Filme` (`cod_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornece_TipoMidia1`
    FOREIGN KEY (`cod_tipomidia`)
    REFERENCES `locadora`.`TipoMidia` (`cod_tipomidia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Locacao` (
  `cod_locacao` INT NOT NULL,
  `data_locacao` DATE NULL,
  `valor` DOUBLE NULL,
  `Cliente_cod_cliente` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`cod_locacao`),
  INDEX `fk_Locacao_Cliente1_idx` (`Cliente_cod_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Locacao_Cliente1`
    FOREIGN KEY (`Cliente_cod_cliente`)
    REFERENCES `locadora`.`Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`ItemLocado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`ItemLocado` (
  `cod_locacao` INT NOT NULL,
  `ItemFilme_cod_item_filme` INT NOT NULL,
  `ItemFilme_cod_filme` INT NOT NULL,
  `data_dev_prevista` DATE NULL,
  `valor` DOUBLE NULL,
  `status` INT NULL,
  `data_devolucao` DATE NULL,
  PRIMARY KEY (`cod_locacao`, `ItemFilme_cod_item_filme`, `ItemFilme_cod_filme`),
  INDEX `fk_Locacao_has_Filme_Locacao1_idx` (`cod_locacao` ASC) VISIBLE,
  INDEX `fk_ItemLocado_ItemFilme1_idx` (`ItemFilme_cod_item_filme` ASC, `ItemFilme_cod_filme` ASC) VISIBLE,
  CONSTRAINT `fk_Locacao_has_Filme_Locacao1`
    FOREIGN KEY (`cod_locacao`)
    REFERENCES `locadora`.`Locacao` (`cod_locacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemLocado_ItemFilme1`
    FOREIGN KEY (`ItemFilme_cod_item_filme` , `ItemFilme_cod_filme`)
    REFERENCES `locadora`.`ItemFilme` (`cod_item_filme` , `cod_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Reserva` (
  `cod_reserva` INT NOT NULL,
  `data_hora_reserva` DATETIME NULL,
  `cod_cliente` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`cod_reserva`),
  INDEX `fk_Reserva_Cliente1_idx` (`cod_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `locadora`.`Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`ItemReserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`ItemReserva` (
  `cod_reserva` INT NOT NULL,
  `ItemFilme_cod_item_filme` INT NOT NULL,
  `ItemFilme_cod_filme` INT NOT NULL,
  PRIMARY KEY (`cod_reserva`, `ItemFilme_cod_item_filme`, `ItemFilme_cod_filme`),
  INDEX `fk_Reserva_has_Filme_Reserva1_idx` (`cod_reserva` ASC) VISIBLE,
  INDEX `fk_ItemReserva_ItemFilme1_idx` (`ItemFilme_cod_item_filme` ASC, `ItemFilme_cod_filme` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_has_Filme_Reserva1`
    FOREIGN KEY (`cod_reserva`)
    REFERENCES `locadora`.`Reserva` (`cod_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemReserva_ItemFilme1`
    FOREIGN KEY (`ItemFilme_cod_item_filme` , `ItemFilme_cod_filme`)
    REFERENCES `locadora`.`ItemFilme` (`cod_item_filme` , `cod_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`FormaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`FormaPagamento` (
  `cod_formapagamento` INT NOT NULL,
  `descricao` VARCHAR(10) NULL,
  PRIMARY KEY (`cod_formapagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Pagamento` (
  `cod_pagamento` INT NOT NULL,
  `loc_cod_locacao` INT NOT NULL,
  `valor` DOUBLE NULL,
  `valor_desconto` DOUBLE NULL,
  `valor_multa` DOUBLE NULL,
  `valor_total` DOUBLE NULL,
  `FormaPagamento_cod_formapagamento` INT NOT NULL,
  PRIMARY KEY (`cod_pagamento`, `loc_cod_locacao`),
  INDEX `fk_Pagamento_Locacao1_idx` (`loc_cod_locacao` ASC) VISIBLE,
  INDEX `fk_Pagamento_FormaPagamento1_idx` (`FormaPagamento_cod_formapagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Locacao1`
    FOREIGN KEY (`loc_cod_locacao`)
    REFERENCES `locadora`.`Locacao` (`cod_locacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_FormaPagamento1`
    FOREIGN KEY (`FormaPagamento_cod_formapagamento`)
    REFERENCES `locadora`.`FormaPagamento` (`cod_formapagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Cheque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Cheque` (
  `Pagamento_cod_pagamento` INT NOT NULL,
  `Pagamento_loc_cod_locacao` INT NOT NULL,
  `banco` VARCHAR(20) NULL,
  `agencia` INT NULL,
  `conta` INT NULL,
  `num_cheque` INT NULL,
  PRIMARY KEY (`Pagamento_cod_pagamento`, `Pagamento_loc_cod_locacao`),
  CONSTRAINT `fk_Cheque_Pagamento1`
    FOREIGN KEY (`Pagamento_cod_pagamento` , `Pagamento_loc_cod_locacao`)
    REFERENCES `locadora`.`Pagamento` (`cod_pagamento` , `loc_cod_locacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Cartao` (
  `Pagamento_cod_pagamento` INT NOT NULL,
  `Pagamento_loc_cod_locacao` INT NOT NULL,
  `operadora` VARCHAR(45) NULL,
  `numero` VARCHAR(20) NULL,
  `data_autorizacao` DATE NULL,
  PRIMARY KEY (`Pagamento_cod_pagamento`, `Pagamento_loc_cod_locacao`),
  CONSTRAINT `fk_Cartao_Pagamento1`
    FOREIGN KEY (`Pagamento_cod_pagamento` , `Pagamento_loc_cod_locacao`)
    REFERENCES `locadora`.`Pagamento` (`cod_pagamento` , `loc_cod_locacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`GrupoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`GrupoUsuario` (
  `cod_grupo` INT NOT NULL,
  `nome_grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Usuario` (
  `cod_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(200) NULL,
  `GrupoUsuario_cod_grupo` INT NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  INDEX `fk_Usuario_GrupoUsuario1_idx` (`GrupoUsuario_cod_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_GrupoUsuario1`
    FOREIGN KEY (`GrupoUsuario_cod_grupo`)
    REFERENCES `locadora`.`GrupoUsuario` (`cod_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Modulo` (
  `cod_modulo` INT NOT NULL,
  `nome_modulo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locadora`.`Permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locadora`.`Permissoes` (
  `cod_permissoes` INT NOT NULL,
  `Modulo_cod_modulo` INT NOT NULL,
  `GrupoUsuario_cod_grupo` INT NOT NULL,
  `nivel_acesso` INT NULL,
  PRIMARY KEY (`cod_permissoes`, `Modulo_cod_modulo`, `GrupoUsuario_cod_grupo`),
  INDEX `fk_Permissoes_Modulo1_idx` (`Modulo_cod_modulo` ASC) VISIBLE,
  INDEX `fk_Permissoes_GrupoUsuario1_idx` (`GrupoUsuario_cod_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_Permissoes_Modulo1`
    FOREIGN KEY (`Modulo_cod_modulo`)
    REFERENCES `locadora`.`Modulo` (`cod_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permissoes_GrupoUsuario1`
    FOREIGN KEY (`GrupoUsuario_cod_grupo`)
    REFERENCES `locadora`.`GrupoUsuario` (`cod_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
